name: TechTrends - Package with Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: techtrends-project
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Debug Variables
      run: |
        echo "DOCKER_USERNAME from secret: ${{ secrets.DOCKERHUB_USERNAME }}"
        echo "DOCKER_USERNAME from env: ${{ env.DOCKER_USERNAME }}"
        echo "DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}"

    - name: Set Docker Tag
      run: echo "DOCKER_TAG=emmanueldeabreu/techtrends-project:latest" >> $GITHUB_ENV

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.DOCKER_TAG }}